### ISSUE TITLE
Not able to use vanilla-integration

### ISSUE THREAD

**Issue by ankitapage** [GrupaZero/core#1]
The gzero vanilla-integration needs minimum PHP version to >=5.4.0 but also needs gzero core version to be "dev-master". But gzero core needs a PHP version to be minimum >=5.5. So, how can I use gzero vanilla-integration on PHP version >=5.4.0

**Comment by PSkierniewski** [comment]
Hi, php >=5.5 i a Laravel 5 dependency which whole package is based on, we migrate to Laravel 5 recently but vanilla-integration has not yet been tested with new Laravel.

vanilla-integration dependencies has been updated to match Laravel 5 but it still may need some fixes to work properly, we will test in incoming days.
